# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RSPX8pr1mhaSdoATnYCrp4kTwP1rrju
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install nvcc4jupyter
# %load_ext nvcc4jupyter

# Commented out IPython magic to ensure Python compatibility.
# %%cuda
# #include <stdio.h>
# 
# __global__ void vectorAdd(int *a, int *b, int *c, int n) {
#     int i = blockIdx.x * blockDim.x + threadIdx.x;
#     if (i < n) c[i] = a[i] + b[i];
# }
# 
# int main() {
#     int n = 5;
#     int a[] = {1, 2, 3, 4, 5};
#     int b[] = {10, 20, 30, 40, 50};
#     int c[5];
# 
#     int *da, *db, *dc;
#     cudaMalloc(&da, n * sizeof(int));
#     cudaMalloc(&db, n * sizeof(int));
#     cudaMalloc(&dc, n * sizeof(int));
# 
#     cudaMemcpy(da, a, n * sizeof(int), cudaMemcpyHostToDevice);
#     cudaMemcpy(db, b, n * sizeof(int), cudaMemcpyHostToDevice);
# 
#     vectorAdd<<<1, n>>>(da, db, dc, n);
# 
#     cudaMemcpy(c, dc, n * sizeof(int), cudaMemcpyDeviceToHost);
# 
#     for (int i = 0; i < n; i++)
#         printf("%d + %d = %d\n", a[i], b[i], c[i]);
# 
#     return 0;
# }

