# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RSPX8pr1mhaSdoATnYCrp4kTwP1rrju
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install nvcc4jupyter
# %load_ext nvcc4jupyter

# Commented out IPython magic to ensure Python compatibility.
# %%cuda
# #include <stdio.h>
# 
# __global__ void matMul(int *a, int *b, int *c, int n) {
#     int row = blockIdx.y * blockDim.y + threadIdx.y;
#     int col = blockIdx.x * blockDim.x + threadIdx.x;
#     int sum = 0;
#     if (row < n && col < n) {
#         for (int k = 0; k < n; k++)
#             sum += a[row * n + k] * b[k * n + col];
#         c[row * n + col] = sum;
#     }
# }
# 
# int main() {
#     int n = 2;
#     int a[] = {1, 2, 3, 4};
#     int b[] = {5, 6, 7, 8};
#     int c[4];
# 
#     int *da, *db, *dc;
#     cudaMalloc(&da, n * n * sizeof(int));
#     cudaMalloc(&db, n * n * sizeof(int));
#     cudaMalloc(&dc, n * n * sizeof(int));
# 
#     cudaMemcpy(da, a, n * n * sizeof(int), cudaMemcpyHostToDevice);
#     cudaMemcpy(db, b, n * n * sizeof(int), cudaMemcpyHostToDevice);
# 
#     dim3 block(2, 2);
#     dim3 grid(1, 1);
#     matMul<<<grid, block>>>(da, db, dc, n);
# 
#     cudaMemcpy(c, dc, n * n * sizeof(int), cudaMemcpyDeviceToHost);
# 
#     printf("Result Matrix:\n");
#     for (int i = 0; i < n; i++) {
#         for (int j = 0; j < n; j++)
#             printf("%d ", c[i * n + j]);
#         printf("\n");
#     }
# 
#     return 0;
# }

